# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: build
        run: xcodebuild build -scheme PWTheming -destination 'platform=iOS Simulator,name=iPhone 14'
      - name: test
        run: xcodebuild test -scheme PWTheming -destination 'platform=iOS Simulator,name=iPhone 14'
